import { LegalSection, LegalShell } from "@/components/app/LegalShell";

export const metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Dealscope.",
};

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" lastUpdated="8 May 2026">
      <p>
        These terms set out how you can use Dealscope (&quot;the Service&quot;),
        operated by Daramola Consulting Ltd (&quot;we&quot;, &quot;us&quot;).
        By creating an account or using the Service you agree to be bound by
        these terms. If you don&apos;t agree, please don&apos;t use the
        Service.
      </p>

      <LegalSection id="not-advice" title="1. Not financial advice">
        <p>
          Dealscope is an <strong>analytical research tool</strong>. It is not a
          regulated financial service and we are not authorised by the FCA. Our
          scores, reports, and figures are for research purposes only and must
          not be treated as a recommendation, advice, or instruction to buy,
          sell, finance, or hold any property. Always commission a survey,
          valuation, and legal review before any property transaction, and
          consult a qualified mortgage broker.
        </p>
      </LegalSection>

      <LegalSection id="accounts" title="2. Your account">
        <p>
          You must be 18 or over and able to enter into a binding contract to
          use the Service. You&apos;re responsible for keeping your login
          credentials confidential and for any activity on your account.
        </p>
        <p>
          You must give accurate information when signing up. We may suspend or
          terminate accounts that we reasonably believe have been used to
          impersonate, defraud, or violate these terms.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" title="3. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>
            Use the Service to break any law or to infringe anyone&apos;s
            rights.
          </li>
          <li>
            Scrape, crawl, reverse-engineer, or otherwise extract bulk data
            from Dealscope outside of the documented features.
          </li>
          <li>
            Resell or commercially redistribute reports, scores, or data
            without our written permission.
          </li>
          <li>
            Interfere with the Service, attempt to gain unauthorised access,
            or run security probes without our written authorisation.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="data-sources" title="4. Third-party data">
        <p>
          Scores and figures incorporate data from third-party sources
          (including the UK Land Registry, ONS, council licensing registers,
          and listing portals). This data may be incomplete, delayed, or
          inaccurate. We don&apos;t warrant that any score, figure, or report
          is correct, current, or fit for any particular purpose.
        </p>
      </LegalSection>

      <LegalSection id="ip" title="5. Intellectual property">
        <p>
          The Dealscope name, logo, design, and methodology are owned by
          Daramola Consulting Ltd. The scores and reports you generate are
          yours to use for your own research and decision-making, including
          sharing them with brokers, accountants, and partners. You must not
          remove disclaimers from reports or PDFs.
        </p>
      </LegalSection>

      <LegalSection id="ai" title="6. AI-generated content">
        <p>
          Some output (deal reports, listing extractions) is generated by
          large language models. These outputs can contain errors. You should
          verify any specific claim against the underlying data and your own
          professional advice before acting on it.
        </p>
      </LegalSection>

      <LegalSection id="pricing" title="7. Pricing and payment">
        <p>
          During early access, Dealscope is free with a 5-report-per-month
          quota. Paid tiers will be introduced; you&apos;ll be notified before
          any subscription is activated on your account, and you won&apos;t be
          charged without explicit consent.
        </p>
      </LegalSection>

      <LegalSection id="termination" title="8. Termination">
        <p>
          You can close your account at any time by contacting us. We can
          suspend or terminate your account if you breach these terms,
          attempt to misuse the Service, or fail to pay any subscription
          (when paid plans launch). We&apos;ll usually give you notice first
          unless we judge that doing so would be harmful.
        </p>
      </LegalSection>

      <LegalSection id="liability" title="9. Liability">
        <p>
          Nothing in these terms limits our liability for fraud or for death
          or personal injury caused by our negligence, or any liability that
          can&apos;t be excluded under English law.
        </p>
        <p>
          Subject to the above, our total liability to you in connection with
          the Service is capped at the greater of (i) £100 or (ii) the fees
          you paid us in the 12 months before the claim arose. We are not
          liable for investment losses, lost profits, lost deals, or
          consequential losses arising from your use of the Service. You use
          Dealscope at your own risk.
        </p>
      </LegalSection>

      <LegalSection id="changes" title="10. Changes to these terms">
        <p>
          We may update these terms from time to time. We&apos;ll show the
          updated date at the top, and for material changes we&apos;ll notify
          you by email or in-app banner before they take effect.
        </p>
      </LegalSection>

      <LegalSection id="law" title="11. Governing law">
        <p>
          These terms are governed by the laws of England and Wales. Any
          disputes will be subject to the exclusive jurisdiction of the
          English courts.
        </p>
      </LegalSection>
    </LegalShell>
  );
}
